"""
Study Hub models.

We CACHE every generated lesson by (grade, syllabus, subject, chapter, language).
Why? Generating with Ollama is slow (~10s). If 100 students ask about
"Class 7 Maths Chapter 3 - Integers", we generate once and reuse.
"""
from django.db import models
from django.conf import settings


class StudyLesson(models.Model):
    """A lesson summary generated by the AI for a specific chapter."""

    SYLLABUS_CHOICES = [
        ("CBSE", "CBSE"),
        ("ICSE", "ICSE"),
        ("KARNATAKA", "Karnataka State Board"),
        ("MAHARASHTRA", "Maharashtra State Board"),
        ("TAMILNADU", "Tamil Nadu State Board"),
        ("WESTBENGAL", "West Bengal State Board"),
        ("ANDHRAPRADESH", "Andhra Pradesh State Board"),
        ("OTHER", "Other"),
    ]

    LANGUAGE_CHOICES = [
        ("en", "English"),
        ("hi", "Hindi"),
        ("ta", "Tamil"),
        ("te", "Telugu"),
        ("bn", "Bengali"),
        ("kn", "Kannada"),
        ("mr", "Marathi"),
    ]

    grade = models.IntegerField()
    syllabus = models.CharField(max_length=20, choices=SYLLABUS_CHOICES, default="CBSE")
    subject = models.CharField(max_length=80)
    chapter = models.CharField(max_length=200)
    language = models.CharField(max_length=5, choices=LANGUAGE_CHOICES, default="en")

    # The full AI-generated lesson (markdown text)
    summary = models.TextField()
    key_points = models.JSONField(default=list)  # list of strings

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # If a row already exists for this combination, we reuse it
        unique_together = [("grade", "syllabus", "subject", "chapter", "language")]
        indexes = [
            models.Index(fields=["grade", "syllabus", "subject"]),
        ]

    def __str__(self):
        return f"Grade {self.grade} - {self.subject} - {self.chapter} ({self.language})"


class LessonView(models.Model):
    """Tracks which student viewed which lesson - for analytics."""

    student = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="lesson_views"
    )
    lesson = models.ForeignKey(StudyLesson, on_delete=models.CASCADE, related_name="views")
    viewed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-viewed_at"]
