# Generated by Django 4.2.11 on 2026-05-06 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('quizzes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='resources.chapter'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['student', 'quiz'], name='quizzes_stu_student_b32d66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentquizattempt',
            unique_together={('student', 'quiz')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['grade', 'subject'], name='quizzes_qui_grade_06e5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz'], name='quizzes_que_quiz_id_ffb3fb_idx'),
        ),
    ]
