# Generated by Django 4.2.11 on 2026-05-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='chapter',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='grade',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='syllabus',
            field=models.CharField(default='CBSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('kn', 'Kannada'), ('mr', 'Marathi')], default='en', max_length=5),
        ),
    ]
