# Generated by Django 4.2.11 on 2026-05-06 01:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('learning_objectives', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['grade', 'subject', 'chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('lesson', 'Lesson'), ('pdf', 'PDF Notes'), ('video', 'Video'), ('notes', 'Handwritten Notes'), ('exercise', 'Exercise/Practice')], default='lesson', max_length=20)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('subject', models.CharField(choices=[('kannada', 'Kannada'), ('english', 'English'), ('maths', 'Mathematics'), ('science', 'Science'), ('social_science', 'Social Science')], max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.chapter')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kannada', 'Kannada'), ('english', 'English'), ('maths', 'Mathematics'), ('science', 'Science'), ('social_science', 'Social Science')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='resources.subject'),
        ),
        migrations.CreateModel(
            name='StudentResourceDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_offline_cached', models.BooleanField(default=False)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='resources.resource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_resources', to='users.student')),
            ],
            options={
                'ordering': ['-downloaded_at'],
                'unique_together': {('student', 'resource')},
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['grade', 'subject'], name='resources_r_grade_dbcdde_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['subject', 'grade'], name='resources_c_subject_c84bc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'grade', 'chapter_number')},
        ),
    ]
