# Generated by Django 4.2.11 on 2026-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.CharField(choices=[('kannada', 'Kannada'), ('hindi', 'Hindi'), ('marathi', 'Marathi'), ('english', 'English'), ('maths', 'Mathematics'), ('science', 'Science'), ('social_science', 'Social Science')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('kannada', 'Kannada'), ('hindi', 'Hindi'), ('marathi', 'Marathi'), ('english', 'English'), ('maths', 'Mathematics'), ('science', 'Science'), ('social_science', 'Social Science')], max_length=50, unique=True),
        ),
    ]
