# Generated by Django 4.2.11 on 2026-05-07 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('syllabus', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('KARNATAKA', 'Karnataka State Board'), ('MAHARASHTRA', 'Maharashtra State Board'), ('TAMILNADU', 'Tamil Nadu State Board'), ('WESTBENGAL', 'West Bengal State Board'), ('ANDHRAPRADESH', 'Andhra Pradesh State Board'), ('OTHER', 'Other')], default='CBSE', max_length=20)),
                ('subject', models.CharField(max_length=80)),
                ('chapter', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('kn', 'Kannada'), ('mr', 'Marathi')], default='en', max_length=5)),
                ('summary', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['grade', 'syllabus', 'subject'], name='study_hub_s_grade_4bac42_idx')],
                'unique_together': {('grade', 'syllabus', 'subject', 'chapter', 'language')},
            },
        ),
        migrations.CreateModel(
            name='LessonView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='study_hub.studylesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
